<a href="https://colab.research.google.com/github/prince-musonda/my-journey-to-artificial-intelligence/blob/main/pytorch%20basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
heights = [189, 170, 189, 163, 183, 171, 185,
 168, 173, 183, 173, 173, 175, 178,
 183, 193, 178, 173, 174, 183, 183,
 180, 168, 180, 170, 178, 182, 180,
 183, 178, 182, 188, 175, 179, 183,
 193, 182, 183, 177, 185, 188, 188,
 182, 185, 191, 183]

In [3]:
import torch

heights_tensor = torch.tensor(heights, dtype=torch.float64)

In [8]:
tensor1 = torch.zeros(2,3)
print(tensor1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [20]:
tensor2 = torch.ones(3,4,5)
print(tensor2)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])


In [21]:
first_five = heights_tensor[:5]
print(first_five)

tensor([189., 170., 189., 163., 183.], dtype=torch.float64)


In [23]:
feets_in_height = heights_tensor / 30.48
feets_in_height

tensor([6.2008, 5.5774, 6.2008, 5.3478, 6.0039, 5.6102, 6.0696, 5.5118, 5.6759,
        6.0039, 5.6759, 5.6759, 5.7415, 5.8399, 6.0039, 6.3320, 5.8399, 5.6759,
        5.7087, 6.0039, 6.0039, 5.9055, 5.5118, 5.9055, 5.5774, 5.8399, 5.9711,
        5.9055, 6.0039, 5.8399, 5.9711, 6.1680, 5.7415, 5.8727, 6.0039, 6.3320,
        5.9711, 6.0039, 5.8071, 6.0696, 6.1680, 6.1680, 5.9711, 6.0696, 6.2664,
        6.0039], dtype=torch.float64)

In [30]:
heights_2_measures = torch.cat([heights_tensor, feets_in_height],dim=-1)
heights_2_measures

tensor([189.0000, 170.0000, 189.0000, 163.0000, 183.0000, 171.0000, 185.0000,
        168.0000, 173.0000, 183.0000, 173.0000, 173.0000, 175.0000, 178.0000,
        183.0000, 193.0000, 178.0000, 173.0000, 174.0000, 183.0000, 183.0000,
        180.0000, 168.0000, 180.0000, 170.0000, 178.0000, 182.0000, 180.0000,
        183.0000, 178.0000, 182.0000, 188.0000, 175.0000, 179.0000, 183.0000,
        193.0000, 182.0000, 183.0000, 177.0000, 185.0000, 188.0000, 188.0000,
        182.0000, 185.0000, 191.0000, 183.0000,   6.2008,   5.5774,   6.2008,
          5.3478,   6.0039,   5.6102,   6.0696,   5.5118,   5.6759,   6.0039,
          5.6759,   5.6759,   5.7415,   5.8399,   6.0039,   6.3320,   5.8399,
          5.6759,   5.7087,   6.0039,   6.0039,   5.9055,   5.5118,   5.9055,
          5.5774,   5.8399,   5.9711,   5.9055,   6.0039,   5.8399,   5.9711,
          6.1680,   5.7415,   5.8727,   6.0039,   6.3320,   5.9711,   6.0039,
          5.8071,   6.0696,   6.1680,   6.1680,   5.9711,   6.06

In [32]:
heights_reshaped = heights_2_measures.reshape((2,-1))
print(heights_reshaped)

tensor([[189.0000, 170.0000, 189.0000, 163.0000, 183.0000, 171.0000, 185.0000,
         168.0000, 173.0000, 183.0000, 173.0000, 173.0000, 175.0000, 178.0000,
         183.0000, 193.0000, 178.0000, 173.0000, 174.0000, 183.0000, 183.0000,
         180.0000, 168.0000, 180.0000, 170.0000, 178.0000, 182.0000, 180.0000,
         183.0000, 178.0000, 182.0000, 188.0000, 175.0000, 179.0000, 183.0000,
         193.0000, 182.0000, 183.0000, 177.0000, 185.0000, 188.0000, 188.0000,
         182.0000, 185.0000, 191.0000, 183.0000],
        [  6.2008,   5.5774,   6.2008,   5.3478,   6.0039,   5.6102,   6.0696,
           5.5118,   5.6759,   6.0039,   5.6759,   5.6759,   5.7415,   5.8399,
           6.0039,   6.3320,   5.8399,   5.6759,   5.7087,   6.0039,   6.0039,
           5.9055,   5.5118,   5.9055,   5.5774,   5.8399,   5.9711,   5.9055,
           6.0039,   5.8399,   5.9711,   6.1680,   5.7415,   5.8727,   6.0039,
           6.3320,   5.9711,   6.0039,   5.8071,   6.0696,   6.1680,   6.1680,
  

In [33]:
uncle_joe_height = heights_reshaped[0,-1]

In [34]:
print(f"uncle Joe's height in centimeters is {uncle_joe_height}")

uncle Joe's height in centimeters is 183.0


In [36]:
median_height = torch.median(heights_reshaped[0])
print(f"the median height is {median_height}")

the median height is 182.0


In [39]:
average_height = torch.mean(heights_reshaped,dim=1)
print(average_height)

tensor([180.0652,   5.9077], dtype=torch.float64)


In [46]:
# tallest president
values, indices = torch.max(heights_reshaped,dim=1)
print(values)
print(indices)

tensor([193.0000,   6.3320], dtype=torch.float64)
tensor([15, 15])
